export const LOAD_HOTELS_BEGIN = 'LOAD_HOTELS_BEGIN';
export const LOAD_HOTELS_SUCCESS = 'LOAD_HOTELS_SUCCESS';
export const LOAD_HOTELS_FAILED = 'LOAD_HOTELS_FAIL';
export const SELECT_HOTEL = 'SELECT_HOTEL';
