export const LOAD_MY_ORDERS_BEGIN = 'LOAD_MY_ORDERS_BEGIN';
export const LOAD_MY_ORDERS_SUCCESS = 'LOAD_MY_ORDERS_SUCCESS';
export const LOAD_MY_ORDERS_FAILED = 'LOAD_MY_ORDERS_FAILED';
export const SELECT_ORDER = 'SELECT_ORDER';
